[package]
name = "grpc-calculator"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13"
tokio = { version = "1", features = ["full"] } 
prost = "0.14" # de/serialize into protobuf

[build-dependencies]
tonic-build = "0.13"

